[versions]
kotlin = "2.1.0"
kotlinx-benchmark = "0.4.13"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.2" }
aoc-inputs-downloader = { id = "com.shykial.aoc.inputs.downloader", version = "0.0.1" }

[libraries]
kotlinx-benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }
